### ISSUE TITLE
Resend Magic Link Error

### ISSUE THREAD

**Issue by jamesdovey** [KennedyNvsf/Authy#2]
I'm trying to use Resend's magic link, it works for creating a new user however when I login for a second time I get hit with an Adapter error: Couldn’t update the user.

It appears the id isn't been passed into the updateUser function.

would love to get this working if you know how to fix it?

**Comment by jamesdovey** [comment]
`async getUserByEmail(email) {
      try {
        const user_qry = `*[_type == "user" && email== "${email}"][0]`;
        const user = await sanityClient.fetch(user_qry);

 // Return id remapped
        return {
          id: user._id,
          ...user,
        };
      } catch (error) {
        throw new Error("Couldn’t get the user");
      }
    }`

**Comment by KennedyNvsf** [comment]
Glad you managed to solve the issue
